<?php

include_once 'lib/defaults.php';

header('Content-Type: text/html; charset=UTF-8');

$title = 'Welcome to Zvini!';

echo
    '<!DOCTYPE html>'
    .'<html style="height: 100%">'
        .'<head>'
            ."<title>$title</title>"
            .'<meta http-equiv="Content-Type"'
            .' content="text/html; charset=UTF-8" />'
            .'<meta name="viewport"'
            .' content="width=device-width, user-scalable=no" />'
            .'<style type="text/css">'
                .'* {'
                    .'margin: 0;'
                    .'padding: 0;'
                    .'font: inherit;'
                    .'box-sizing: border-box;'
                    .'-moz-box-sizing: border-box;'
                .'}'
                .'html, body {'
                    .'height: 100%;'
                    .'white-space: nowrap;'
                    .'text-align: center;'
                    .'background: #444;'
                    .'color: #fff;'
                    .'font: normal 16px/18px Arial, sans-serif;'
                .'}'
                .'h1 {'
                    .'font-weight: bold;'
                    .'font-size: 22px;'
                .'}'
                .'.layout {'
                    .'display: inline-block;'
                    .'vertical-align: middle;'
                .'}'
                .'.layout.aligner {'
                    .'height: 100%;'
                .'}'
                .'.layout.content {'
                    .'padding: 8px;'
                    .'white-space: normal;'
                    .'max-width: 100%;'
                .'}'
                .'a {'
                    .'color: #f70;'
                .'}'
                .'em {'
                    .'border-bottom: 1px dotted;'
                    .'word-wrap: break-word;'
                .'}'
            .'</style>'
        .'</head>'
        .'<body>'
            .'<div class="layout aligner"></div>'
            .'<div class="layout content">'
                ."<h1>$title</h1>"
                .'<br />'
                .'<div>'
                    .'Zvini makes use of "<code>.htaccess</code>" files.'
                    .' Seeing this page means that "<code>.htaccess</code>"'
                    .' files are ignored by your Apache web server.'
                    .' Please, enable "<code>.htaccees</code>"'
                    .' in Apache configuration and then reload the page.'
                .'</div>'
            .'</div>'
        .'</body>'
    .'</html>';
